port: 7890
socks-port: 7891
external-controller: 0.0.0.0:9090
external-ui: "yacd-gh-pages"
ipv6: false
mode: rule
log-level: silent
unified-delay: true
dns:
  enable: true
  ipv6: false
  nameserver:
  - 8.8.8.8
  - 8.8.4.4
  default-nameserver:
  - 8.8.8.8
  - 8.8.4.4



proxies:
  - name: CFT
    server: 104.22.4.240
    port: 443
    type: vless
    uuid: 3b4e6790-7e19-4643-8a37-2d4fc7193a54
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: df.game.naver.com.gatot.wonghd.my.id
    network: ws
    ws-opts:
      path: /
      headers:
        Host: df.game.naver.com.gatot.wonghd.my.id
    udp: true



proxy-groups:
  - name: CLASH FOR TERMUX
    type: select
    proxies:
      - CFT



rules:
  - MATCH,CLASH FOR TERMUX
